# Generated by Django 5.0.1 on 2024-05-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions_health',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions_tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='earnings_allowance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='overtime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pag_ibig',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pay_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='sss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_pay',
            field=models.FloatField(default=0.0),
        ),
    ]
