# Generated by Django 5.0.1 on 2024-05-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_alter_employee_overtime_pay_alter_employee_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowance',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_pay',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.FloatField(null=0),
        ),
    ]
