# Generated by Django 5.0.1 on 2024-05-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_alter_employee_allowance_alter_employee_overtime_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='deductions_health',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions_tax',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='earnings_allowance',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='overtime',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pag_ibig',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pay_cycle',
            field=models.IntegerField(null=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='rate',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='sss',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_pay',
            field=models.FloatField(null=0),
        ),
    ]
